[package]
name = "nfs-daemon"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "nfs-daemon"
path = "src/daemon.rs"

[[bin]]
name = "nfs-client"
path = "src/client.rs"

[dependencies]
# logging
log = "*"
simplelog = "*"
# output
pretty-bytes = "*"
# signals
signal-hook = "*"